// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN6FDhqyITsKzACjz8i-R5--ms-FKd3BM',
    appId: '1:261580791172:web:773fd3959195a13bf191d1',
    messagingSenderId: '261580791172',
    projectId: 'notes-13630',
    authDomain: 'notes-13630.firebaseapp.com',
    storageBucket: 'notes-13630.appspot.com',
    measurementId: 'G-5ZG5Z8DNE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7vSQE3hNYpx28njUsNRh3Hl-DqWyMZtc',
    appId: '1:261580791172:android:24e6ec167f82df41f191d1',
    messagingSenderId: '261580791172',
    projectId: 'notes-13630',
    storageBucket: 'notes-13630.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnNvAVdDZFkXiqkDmZwElcO_mtD2Id-ok',
    appId: '1:261580791172:ios:7dd168bbd7c9eb52f191d1',
    messagingSenderId: '261580791172',
    projectId: 'notes-13630',
    storageBucket: 'notes-13630.appspot.com',
    iosClientId: '261580791172-v8npd0bqpa7k8o2bc6e3trn7rue1idt3.apps.googleusercontent.com',
    iosBundleId: 'gd.rf.szryk',
  );
}
